# Generated by Django 5.2.7 on 2026-08-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fix_missing_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'managed': False},
        ),
    ]
