# Generated by Django 5.2.7 on 2026-02-24 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('benefit_type', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(max_length=100)),
                ('official_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('registration_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schemes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('aadhaar_no', models.CharField(max_length=500, unique=True)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('occupation', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('disability_status', models.BooleanField(default=False)),
                ('pension_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='RuleEngine',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('min_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('required_education', models.CharField(blank=True, max_length=100, null=True)),
                ('disability_required', models.BooleanField(blank=True, null=True)),
                ('pension_required', models.BooleanField(blank=True, null=True)),
                ('occupation_required', models.CharField(blank=True, max_length=100, null=True)),
                ('business_turnover_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('state_required', models.CharField(blank=True, max_length=100, null=True)),
                ('scheme', models.ForeignKey(db_column='scheme_id', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.scheme')),
            ],
            options={
                'db_table': 'rule_engine',
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('grievance_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_text', models.TextField()),
                ('status', models.CharField(default='Open', max_length=100)),
                ('admin_remark', models.TextField(blank=True, null=True)),
                ('raised_on', models.DateTimeField(auto_now_add=True)),
                ('resolved_on', models.DateTimeField(blank=True, null=True)),
                ('scheme', models.ForeignKey(blank=True, db_column='scheme_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.scheme')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to='core.user')),
            ],
            options={
                'db_table': 'grievances',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('scheme', models.ForeignKey(db_column='scheme_id', on_delete=django.db.models.deletion.CASCADE, to='core.scheme')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.user')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='UserCategoryMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mapped_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.user')),
            ],
            options={
                'db_table': 'user_category_mapping',
            },
        ),
        migrations.CreateModel(
            name='UserEligibility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eligibility_status', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True, null=True)),
                ('calculated_on', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(db_column='scheme_id', on_delete=django.db.models.deletion.CASCADE, to='core.scheme')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='core.user')),
            ],
            options={
                'db_table': 'user_eligibility',
                'indexes': [models.Index(fields=['user', 'scheme'], name='user_eligib_user_id_b30c97_idx')],
            },
        ),
    ]
