# Generated by Django 5.2.7 on 2026-02-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('Staff', 'Staff'), ('Admin', 'Admin')], default='Citizen', max_length=20),
        ),
    ]
