# Generated by Django 5.2.7 on 2026-03-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='issue_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='sentiment',
            field=models.CharField(blank=True, default='Neutral', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='urgency',
            field=models.CharField(blank=True, default='Medium', max_length=50, null=True),
        ),
    ]
